#### 1) create a list, accept 5 numbers , store them in the list and finally convert that list to numpy array.


In [2]:
import numpy as np
lst = [int(x) for x in input('Enter 5 numbers').split()]
arr = np.array(lst)
print(arr)
print(type(arr))

Enter 5 numbers 1 2 3 4 5


[1 2 3 4 5]
<class 'numpy.ndarray'>


#### 2) create numpy array of 5 numbers and print their sum

In [9]:
arr = np.arange(1,6)
np.sum(arr)

15

#### 3) create numpy double dimension array of 3*3 to store your initial and display them in a tabular form.

In [16]:
arr = np.arange(1,10).reshape(3,3)
for i in arr:
    for j in i:
        print(j,end=' ')
    print()

1 2 3 
4 5 6 
7 8 9 


#### 4) create one-d numpy array of 12 elements , accept 12 numbers and display them. Now convert this one-d array into (4*3) two-d array and display it in a tabular form.

In [19]:
import numpy as np
lst = [int(x) for x in input('Enter 12 numbers').split()]
arr = np.array(lst)
print(arr)
arr.shape = (4,3)
for i in arr:
    for j in i:
        print(j,end=' ')
    print()

Enter 12 numbers 1 2 3 4 5 6 7 8 9 10 11 12


[ 1  2  3  4  5  6  7  8  9 10 11 12]
1 2 3 
4 5 6 
7 8 9 
10 11 12 


#### 5) create two double dimension array and arrange (stack) them using "axis=0" "axis=1" and  "axis=2".

#### 6) create two one-d arrays and then find out:
	a) common elements of both the array
	b) unique elements of first array
	c) unique elements of second array

In [3]:
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(4,10).reshape(2,3)
print(arr1,'\n\n',arr2)
print('\nIntersection',np.intersect1d(arr1,arr2))
print('\nUnique arr1 elemenets',np.setdiff1d(arr1,arr2))
print('\nUnique arr2 elemenets',np.setdiff1d(arr2,arr1))

[[1 2 3]
 [4 5 6]] 

 [[4 5 6]
 [7 8 9]]

Intersection [4 5 6]

Unique arr1 elemenets [1 2 3]

Unique arr2 elemenets [7 8 9]


#### 7) accept no.of rows and no. of cols from the user , create two-d array accordingly. Now calculate the sum as per "axis=0" and "axis=1"


In [10]:
row = int(input('Enter no of rows: '))
col = int(input('Enter no of columns: '))
arr = np.arange(row*col).reshape(row,col)
print(arr,'\n')
print('Sum axis 0',np.sum(arr,axis=0))
print('Sum axis 1',np.sum(arr,axis=1))

Enter no of rows:  3
Enter no of columns:  4


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Sum axis 0 [12 15 18 21]
Sum axis 1 [ 6 22 38]


#### 8) declare two 2d arrays and calculate the sum as per "axis=0" "axis=1" and "axis=2"

In [29]:
arr = np.arange(1,19).reshape(2,3,3)
print(arr,'\n')
print('Sum axis 0\n',np.sum(arr,axis=0),'\n')
print('Sum axis 1\n',np.sum(arr,axis=1),'\n')
print('Sum axis 2\n',np.sum(arr,axis=2))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]] 

Sum axis 0
 [[11 13 15]
 [17 19 21]
 [23 25 27]] 

Sum axis 1
 [[12 15 18]
 [39 42 45]] 

Sum axis 2
 [[ 6 15 24]
 [33 42 51]]


#### 9) create two-d array ,display it. Now accept a number from user and perform all arithmetic operations on each and every element of the array using that number.

In [34]:
arr = np.arange(10,91,10).reshape(3,3)
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [44]:
n = int(input('Enter a number'))
print('\nArr +',n,'\n',arr+n)
print('\nArr -',n,'\n',arr-n)
print('\nArr x',n,'\n',arr*n)
print('\nArr /',n,'\n',arr/n)

Enter a number 2



Arr + 2 
 [[12 22 32]
 [42 52 62]
 [72 82 92]]

Arr - 2 
 [[ 8 18 28]
 [38 48 58]
 [68 78 88]]

Arr x 2 
 [[ 20  40  60]
 [ 80 100 120]
 [140 160 180]]

Arr / 2 
 [[ 5. 10. 15.]
 [20. 25. 30.]
 [35. 40. 45.]]


#### 10) accept start, end and how many numbers to be generated and then using "linspace" create numpy array.


In [59]:
s = int(input('Enter start'))
e = int(input('Enter end'))
n = int(input('Enter numbers to be generated'))
arr = np.linspace(s,e,n)
print(arr)

Enter start 1
Enter end 100
Enter numbers to be generated 10


[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


#### 11) Create one-d array of 8 numbers and then using "slicing" concept,
	a) print numbers from 1 to 4
	b) print all the numbers from 3rd position
	c) print last 3 numbers

In [73]:
arr = np.arange(1,9)
print(arr)
print(arr[0:4])
print(arr[2:])
print(arr[-3:])

[1 2 3 4 5 6 7 8]
[1 2 3 4]
[3 4 5 6 7 8]
[6 7 8]


#### 12) create 2 d array (3x4) with following values: [[10,20,30,40],[50,60,70,80],[90,100,110,120]].now using array slicing concept display following values
	a) display   50  60  70  80
	b) display 100 and 110
	c) display 30 70 and 110
	d) display 50  60  90 and 100

In [80]:
arr = np.arange(10,121,10).reshape(3,4)
arr

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [82]:
arr[1]

array([50, 60, 70, 80])

In [84]:
arr[2,[1,2]]

array([100, 110])

In [86]:
arr[:,2]

array([ 30,  70, 110])

In [88]:
arr[1:,:2]

array([[ 50,  60],
       [ 90, 100]])